### ISSUE TITLE
Change name from Faithful32-1.8 to Faithful32-1.8.9

### ISSUE THREAD

**Issue by Prospector** [F32Organization/Faithful32-1.8.9#9]

**Comment by kraineff** [comment]
Main version is 1.8)

**Comment by Prospector** [comment]
Nobody is developing for 1.8. Everyone moved onto 1.8.9

**Comment by kraineff** [comment]
Yes, but... :D

**Comment by Prospector** [comment]
1.8.9 has been the recommended version for nearly a week of that is what you were waiting on.
